import { MembershipType } from "@/store/auth-store";

// lib/data.ts
export const ONTOLOGY_COLORS = {
  parties: "text-blue-600",
  obligations: "text-green-600",
  rights: "text-yellow-600",
  conditions: "text-purple-600",
  clauses: "text-pink-600",
  definitions: "text-indigo-600",
  dates: "text-teal-600",
  proceduralPosture: "text-orange-600",
  courtAndJudges: "text-red-600",
  conflicts: "text-amber-600",
  implications: "text-lime-600",
  citationsAndPrecedents: "text-cyan-600",
};

export const soloPlans = [
  {
    id: "trial" as MembershipType,
    title: "Trial",
    price: "$0",
    subtitle: "Start building your legal second brain",
    description: "Case summaries, basic follow-up, and limited search.",
    features: [
      "5 sessions per month",
      "Download PDFs",
      "Case Summaries",
      "Limited follow-up Q&A",
      "Follow-up chat per case",
      "Key clause highlighting",
      "Limited precedent search",
      "Notebook-style storage",
    ],
    cta: "Current plan",
    recommended: false,
    disabled: true,
  },
  {
    id: "plus" as MembershipType,
    title: "Plus",
    price: "$9.99 / mo",
    subtitle: "Focused legal practitioners",
    description: "Deeper insight, richer follow-ups, and trial prep tools.",
    features: [
      "20 sessions per month",
      "Download PDFs",
      "Extended case summarization",
      "Unlimited follow-up Q&A",
      "Mock trial simulator (basic)",
      "Important data & clause extraction",
      "Precedent similarity search",
      "Save & tag legal knowledge",
    ],
    cta: "Get Plus",
    recommended: true,
    disabled: false,
    link: "https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-19K748897R7513945NCGQDCA",
  },
  {
    id: "pro" as MembershipType,
    title: "Pro",
    price: "$49.99 / mo",
    subtitle: "Small firms / power users",
    description:
      "All features plus firm-level collaboration & advanced agents.",
    features: [
      "Unlimited sessions",
      "Download PDFs",
      "Advanced mock trials with branching scenarios",
      "Team-shared case folders",
      "Custom legal agents (e.g., contract reviewer)",
      "Priority processing & search",
      "Firm knowledge graph integration",
    ],
    cta: "Get Pro",
    recommended: false,
    disabled: false,
    link: "https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-7J400757A5379360UNCGQGZQ",
  },
];

export const firmPlans = [
  {
    id: "business" as MembershipType,
    title: "Team",
    price: "$25 / user / mo",
    subtitle: "Collaboration for legal teams",
    description: "Secure shared workspace, firm-level insights.",
    features: [
      "Unlimited sessions",
      "Download PDFs",
      "Shared case dashboards",
      "Role-based access",
      "Audit trail & activity logs",
      "Enterprise integrations (Drive, SharePoint, Slack)",
      "Dedicated onboarding & support",
    ],
    cta: "Buy Team Plan",
    recommended: false,
    disabled: false,
    link: "https://www.paypal.com/webapps/billing/plans/subscribe?plan_id=P-7D383136G64082319NCGQHQA",
  },
  {
    id: "enterprise" as MembershipType,
    title: "Enterprise",
    price: "Custom pricing",
    subtitle: "Full firm-scale deployment",
    description: "Tailored SLAs, compliance, and on-prem options.",
    features: [
      "Everything in Team",
      "Custom PDFs",
      "Custom model fine-tuning (legal domain)",
      "On-prem / hybrid deployment",
      "Advanced security & SOC2/GDPR",
      "Dedicated account strategist",
      "Integrate internal knowledge bases",
    ],
    cta: "Contact Sales",
    recommended: true,
    disabled: false,
  },
];
