export const legalNuggets: string[] = [
  // ---- Indian Nuggets ----
  "In India, you can be jailed for a bounced cheque of ₹500, while scams worth thousands of crores can drag on for decades.",
  "A lawyer in Bihar once argued his client shouldn’t be punished for attempted suicide because he 'failed in that too.'",
  "The Supreme Court of India held a midnight hearing in 2015 to decide the fate of Yakub Memon before his execution.",
  "A man once filed a case against his neighbor’s rooster, claiming its morning crow violated his right to sleep under Article 21.",
  "You need a license to own a gun in India, but no license to argue in court once you have an LL.B.",
  "It was once illegal to fly a kite in India without a permit — because technically it counted as an 'aircraft.'",
  "In 2017, the Supreme Court bizarrely discussed whether peacocks reproduce by sex or by shedding tears.",
  "A judge once dismissed a case saying: 'This petition is like a sea without shore and an ocean without depth.'",
  "One lawyer argued that since cows are considered 'mother,' killing them should be treated as matricide.",
  "India still has a colonial-era law requiring hotel keepers to report 'suspicious foreigners' — drafted in 1860s!",
  "The longest judgment in Indian history was over 21,000 pages — the Ayodhya land dispute (Allahabad HC, 2010).",
  "In India, a person can’t contest elections if they are bankrupt, but they can still become a lawyer and represent clients.",
  "In 2005, Delhi High Court banned smoking in films and TV shows — unless it was 'historically justified.'",
  "An Indian court once had to decide whether astrology counts as a 'science.' The ruling? Yes, it does!",
  "The Indian Penal Code once criminalized keeping pigeons without a license.",
  "During Emergency (1975), habeas corpus petitions were suspended — meaning citizens couldn’t challenge illegal detentions.",
  "In some states, police still need a magistrate’s approval to cut down a tree — colonial forest laws are still active.",
  "The Kerala High Court once ruled that a bar dancer is an 'artist' entitled to labor law protections.",
  "In 2013, an Indian court ruled that 'kissing in public' is not obscene — despite decades of arrests for it.",
  "A lawyer once tried to sue God for not answering prayers. The case was dismissed for 'lack of proper address.'",

  // ---- Quirky Indian Cases ----
  "A litigant once filed a case against Lord Ram, alleging he abandoned Sita unjustly.",
  "A man once sought divorce claiming his wife was 'possessed by ghosts' and the court entertained it.",
  "In 1960s, a case debated whether a stuffed toy elephant could be considered an actual 'elephant' under import laws.",
  "A person once claimed his fundamental rights were violated because his movie ticket seat was broken.",
  "The Allahabad High Court once ruled that loudspeakers are not a fundamental right.",
  "An Indian man sued a hospital claiming his kidney was stolen during surgery — it was later found to be a gall bladder removal error.",
  "In one bizarre PIL, a man demanded that currency notes carry his photo instead of Gandhi’s.",
  "A drunk man once filed a PIL saying exams should be banned because they 'cause stress to youth.'",
  "In Gujarat, a lawyer argued that onions should be declared 'essential religious offering' to stop price rise.",
  "An Indian lawyer once sought a ban on 'Santa Claus,' claiming it hurt Hindu sentiments.",

  // ---- International Sprinkles ----
  "In the U.S., a man once sued himself for violating his own rights — and asked the state to pay damages on his behalf.",
  "In Italy, a judge once ruled that men must not touch their private parts in public — even 'for good luck.'",
  "In China, a man sued his wife for giving birth to an 'ugly baby' — and won, after proving she had cosmetic surgery.",
  "In Canada, a judge had to decide if beer can legally be 'delivered by drone.'",
  "In Germany, escaping prison is not a crime — because the law sees 'freedom' as a basic human instinct.",
  "A man in the U.S. once argued his dog was his co-counsel. The judge disagreed.",
  "In Switzerland, it is illegal to own just one guinea pig — because they get lonely.",
  "In France, it is illegal to name a pig 'Napoleon.'",
  "In Japan, it is illegal to dance in clubs after midnight (law changed in 2015).",
  "In Thailand, stepping on currency is illegal — because it has the King’s face.",

  // ---- Lawyer Life Nuggets ----
  "Lawyers once wore wigs in Indian courts. The practice was dropped post-Independence, but still lives in the UK.",
  "Did you know? Black coats for lawyers were chosen to symbolize 'authority and humility.'",
  "A 2019 study found that Indian lawyers file over 2 million adjournment requests every year.",
  "The Supreme Court once banned judges from taking gifts — even mango boxes during summer season.",
  "In India, a lawyer can represent themselves in court — and they usually make the worst clients.",
  "The Latin phrase 'Justice delayed is justice denied' is cited so often in Indian courts, it could have its own statute number.",
  "There’s a legal maxim: 'Actio personalis moritur cum persona' — personal cases die with the person. Except in Bollywood, where sequels keep them alive.",
  "In India, lawyers often joke: The most powerful word in court isn’t 'Objection,' but 'Adjournment.'",
  "Some lawyers in India still argue cases with 10kg of books even when the same laws are available on their phones.",
  "A Bombay lawyer once said: 'The strongest case is not in law, but in the Tupperware carrying your client’s snacks.'",
];
