import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const campaignDate = "2026-07-02";
const trackerFile = join(root, "docs", "outreach", "claimbrief-pipeline-tracker.csv");
const summaryFile = join(
  root,
  "docs",
  "outreach",
  "generated",
  `claimbrief-pipeline-summary-${campaignDate}.md`
);

const headers = [
  "company",
  "contact",
  "channel",
  "status",
  "next_action",
  "next_action_date",
  "last_touch_date",
  "reply_bucket",
  "packet_received",
  "sample_delivered",
  "payment_status",
  "expected_value",
  "notes",
];

const parseArgs = (argv) => {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith("--")) {
      continue;
    }
    const key = token.slice(2);
    const next = argv[index + 1];
    if (!next || next.startsWith("--")) {
      args[key] = "true";
      continue;
    }
    args[key] = next;
    index += 1;
  }
  return args;
};

const parseCsv = (text) => {
  const rows = [];
  let current = [];
  let field = "";
  let inQuotes = false;

  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    const next = text[index + 1];

    if (char === '"' && inQuotes && next === '"') {
      field += '"';
      index += 1;
      continue;
    }

    if (char === '"') {
      inQuotes = !inQuotes;
      continue;
    }

    if (char === "," && !inQuotes) {
      current.push(field);
      field = "";
      continue;
    }

    if ((char === "\n" || char === "\r") && !inQuotes) {
      if (char === "\r" && next === "\n") {
        index += 1;
      }
      current.push(field);
      field = "";
      if (current.some((value) => value.length > 0)) {
        rows.push(current);
      }
      current = [];
      continue;
    }

    field += char;
  }

  if (field.length > 0 || current.length > 0) {
    current.push(field);
    rows.push(current);
  }

  const [csvHeaders, ...data] = rows;
  if (!csvHeaders) {
    return [];
  }

  return data.map((row) =>
    Object.fromEntries(csvHeaders.map((header, index) => [header, row[index] || ""]))
  );
};

const toCsv = (rows) => {
  const escapeCell = (value) => {
    const stringValue = String(value ?? "");
    if (/[",\r\n]/.test(stringValue)) {
      return `"${stringValue.replace(/"/g, '""')}"`;
    }
    return stringValue;
  };

  return [
    headers.join(","),
    ...rows.map((row) => headers.map((header) => escapeCell(row[header])).join(",")),
  ].join("\n");
};

const countBy = (rows, key) =>
  rows.reduce((counts, row) => {
    const value = row[key] || "blank";
    counts[value] = (counts[value] || 0) + 1;
    return counts;
  }, {});

const tableFromCounts = (counts) => {
  const entries = Object.entries(counts).sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  return entries.length
    ? entries.map(([label, count]) => `| ${label} | ${count} |`).join("\n")
    : "| none | 0 |";
};

const compactRows = (rows) =>
  rows
    .slice(0, 12)
    .map(
      (row) =>
        `| ${row.company} | ${row.channel} | ${row.status || "blank"} | ${row.next_action || "blank"} | ${row.last_touch_date || ""} |`
    )
    .join("\n") || "| none |  |  |  |  |";

const writeSummary = (rows) => {
  const notSentEmails = rows.filter(
    (row) => row.status === "not_sent" && row.next_action === "send_email"
  );
  const notSentForms = rows.filter(
    (row) => row.status === "not_sent" && row.next_action === "submit_form_or_call"
  );
  const followUps = rows.filter((row) => (row.next_action || "").includes("follow"));
  const packetQueue = rows.filter(
    (row) => row.packet_received === "yes" && row.sample_delivered !== "yes"
  );
  const closeQueue = rows.filter(
    (row) => row.sample_delivered === "yes" && row.payment_status !== "paid"
  );

  const report = `# ClaimBrief Pipeline Summary - ${campaignDate}

Generated by \`npm run outreach:claimbrief:tracker\`.

## Counts

| Status | Count |
| --- | ---: |
${tableFromCounts(countBy(rows, "status"))}

| Next Action | Count |
| --- | ---: |
${tableFromCounts(countBy(rows, "next_action"))}

| Payment Status | Count |
| --- | ---: |
${tableFromCounts(countBy(rows, "payment_status"))}

## Immediate Queues

- Email leads not sent: ${notSentEmails.length}
- Form/call leads not attempted: ${notSentForms.length}
- Follow-ups queued: ${followUps.length}
- Packets waiting for sample: ${packetQueue.length}
- Delivered samples waiting for close: ${closeQueue.length}

## Next Email Sends

| Company | Channel | Status | Next Action | Last Touch |
| --- | --- | --- | --- | --- |
${compactRows(notSentEmails)}

## Next Form Or Call Attempts

| Company | Channel | Status | Next Action | Last Touch |
| --- | --- | --- | --- | --- |
${compactRows(notSentForms)}

## Close Queue

| Company | Channel | Status | Next Action | Last Touch |
| --- | --- | --- | --- | --- |
${compactRows([...packetQueue, ...closeQueue])}
`;

  writeFileSync(summaryFile, report);
  return report;
};

const printHelp = () => {
  console.log(`ClaimBrief tracker helper

Summary:
  npm run outreach:claimbrief:tracker

Update one company:
  npm run outreach:claimbrief:tracker -- --company "Palco Claims" --status sent --next-action follow_up_48h --last-touch-date 2026-07-02 --append-note "sent first email"

Supported fields:
  --contact
  --status
  --next-action
  --next-action-date
  --last-touch-date
  --reply-bucket
  --packet-received yes|no
  --sample-delivered yes|no
  --payment-status
  --expected-value
  --set-note
  --append-note
`);
};

if (!existsSync(trackerFile)) {
  throw new Error(`Missing tracker file: ${trackerFile}`);
}

const args = parseArgs(process.argv.slice(2));
if (args.help) {
  printHelp();
  process.exit(0);
}

const rows = parseCsv(readFileSync(trackerFile, "utf8"));

if (args.company) {
  const query = args.company.toLowerCase();
  const exactMatches = rows.filter((row) => row.company.toLowerCase() === query);
  const fuzzyMatches = rows.filter((row) => row.company.toLowerCase().includes(query));
  let matches = exactMatches.length ? exactMatches : fuzzyMatches;

  if (args.contact && matches.length > 1) {
    const contactQuery = args.contact.toLowerCase();
    matches = matches.filter(
      (row) =>
        row.contact.toLowerCase() === contactQuery ||
        row.contact.toLowerCase().includes(contactQuery)
    );
  }

  if (matches.length !== 1) {
    console.error(`Expected exactly one company match for "${args.company}", found ${matches.length}.`);
    matches.slice(0, 12).forEach((row) => console.error(`- ${row.company}`));
    process.exit(1);
  }

  const row = matches[0];
  const updates = {
    status: args.status,
    next_action: args["next-action"],
    next_action_date: args["next-action-date"],
    last_touch_date: args["last-touch-date"],
    reply_bucket: args["reply-bucket"],
    packet_received: args["packet-received"],
    sample_delivered: args["sample-delivered"],
    payment_status: args["payment-status"],
    expected_value: args["expected-value"],
  };

  for (const [key, value] of Object.entries(updates)) {
    if (value != null) {
      row[key] = value;
    }
  }

  if (args["set-note"] != null) {
    row.notes = args["set-note"];
  }

  if (args["append-note"] != null) {
    const separator = row.notes ? " | " : "";
    row.notes = `${row.notes || ""}${separator}${args["append-note"]}`;
  }

  writeFileSync(trackerFile, toCsv(rows));
  console.log(`Updated ${row.company}`);
}

writeSummary(rows);
console.log(`Tracker rows: ${rows.length}`);
console.log(`Summary: ${summaryFile}`);
